#!/bin/sh

# Set these paths appropriately

BIN=/home/franz/software/TreeTagger/bin
CMD=/home/franz/software/TreeTagger/cmd
LIB=/home/franz/software/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
